[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
hyperevm = "${HYPEREVM_TESTNET_RPC}"

[etherscan]
hyperevm = { key = "${HYPEREVM_ETHERSCAN_API_KEY}" }

remappings = [
    "@solady-tokens/=lib/solady/src/tokens/"
]