[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/"
]

[rpc_endpoints]
hyperevm = "${HYPEREVM_TESTNET_RPC}"

[etherscan]
hyperevm = { key = "${HYPEREVM_ETHERSCAN_API_KEY}" }

